apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ejbca.fullname" . }}
  labels:
    {{- include "ejbca.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  # Adding for stateful set coming in a later PR
  #{{- if eq .Values.services.proxyHttp.type "LoadBalancer" }}
  #serviceName: {{ include "ejbca.fullname" . }}
  #{{- end }}
  {{- if .Values.updateStrategy }}
  strategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ejbca.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ejbca.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ejbca.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}  
      {{- if or .Values.nginx.enabled .Values.ejbca.initContainers }}
      initContainers:
        {{- if and .Values.nginx.enabled (not .Values.nginx.mountInternalNginxCert) }}
        - name: {{ template "ejbca.fullname" . }}-init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: {{- include "ejbca.ejbcaDeploymentParameters" . | nindent 12 }}
          {{- with .Values.ejbca.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: 
            - "/bin/sh"
            - "-c"
            - |
              /opt/keyfactor/bin/start.sh &
              until [ -f /opt/keyfactor/appserver/standalone/deployments/ejbca.ear.deployed ]; do sleep 5; done
              until [[ $(/opt/keyfactor/bin/ejbca.sh roles listadmins --role "Super Administrator Role" | grep -v 'USERNAME TYPE_EQUALCASE "ejbca"') ]]; do sleep 5; done
              sleep 5
              /opt/keyfactor/bin/ejbca.sh ra addendentity --username '{{ .Values.nginx.host }}' --dn 'CN={{ .Values.nginx.host }}' --caname 'ManagementCA' --type 1 --token PEM --altname 'dNSName={{ .Values.nginx.host }}' --certprofile SERVER --password NOTUSED
              /opt/keyfactor/bin/ejbca.sh ra setendentitystatus --username '{{ .Values.nginx.host }}' -S 10
              /opt/keyfactor/bin/ejbca.sh ra setclearpwd '{{ .Values.nginx.host }}' NOTUSED
              /opt/keyfactor/bin/ejbca.sh batch '{{ .Values.nginx.host }}' -dir /tmp/nginx/ssl/
          volumeMounts:
          - name: nginx-cert
            mountPath: /tmp/nginx/ssl
          {{- if .Values.ejbca.useH2Persistence }}
          - name: ejbca-h2-persistence
            mountPath: /mnt/persistent/
          {{- end }}
          {{- if .Values.ejbca.importEjbcaConfFiles }}
          - name: ejbca-config-conf-files
            mountPath: /opt/keyfactor/ejbca/conf/
          {{- end }}
        {{- end }}
        {{- if .Values.ejbca.initContainers }}
          {{- toYaml .Values.ejbca.initContainers | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        {{- if .Values.nginx.enabled }}
        - name: {{ template "ejbca.fullname" . }}-nginx
          image: nginx:alpine
          ports:
          {{- if .Values.nginx.service.httpPort }}
          - name: nginx-http
            containerPort: 80
          {{- end }}
          {{- if .Values.nginx.service.httpsPort }}
          - name: nginx-https
            containerPort: 443
          {{- end }}
          startupProbe:
            tcpSocket:
              port: 443
          livenessProbe:
            tcpSocket:
              port: 443
          volumeMounts:
            - name: {{ template "ejbca.fullname" . }}-nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            {{- if .Values.nginx.mountInternalNginxCert }}
            - name: nginx-cert-provided
              mountPath: /etc/nginx/ssl/pem/
            {{- else }}
            - name: nginx-cert
              mountPath: /etc/nginx/ssl/
            {{- end }}
        {{- end }}
        - name: {{ template "ejbca.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: {{- include "ejbca.ejbcaDeploymentParameters" . | nindent 12 }}
            {{- if .Values.services.proxyAJP.enabled }}
            - name: PROXY_AJP_BIND
              value: {{ .Values.services.proxyAJP.bindIP }}
            {{- end }}
            {{- if .Values.services.proxyHttp.enabled }}
            - name: PROXY_HTTP_BIND
              value: {{ .Values.services.proxyHttp.bindIP }}
            {{- end }}
          {{- with .Values.ejbca.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          lifecycle:
            postStart:
              exec:
                command: 
                  - "/bin/sh"
                  - "-c"
                  - |
                    {{- if not .Values.ejbca.importEjbcaConfFiles }}
                    sed -i s/https=443/https={{- include "ejbca.ejbcaHttpsPort" . -}}/g /opt/primekey/ejbca/conf/web.properties
                    sed -i s/pubhttp=80/pubhttp={{- include "ejbca.ejbcaPubhttpPort" . -}}/g /opt/primekey/ejbca/conf/web.properties
                    {{- end }}
                    {{- if and (hasKey .Values.ejbca "superadminPasswordOverride") (eq .Values.ejbca.env.TLS_SETUP_ENABLED "true") }}
                    until [ -f /opt/keyfactor/appserver/standalone/deployments/ejbca.ear.deployed ]; do sleep 5; done
                    until [[ $(/opt/keyfactor/bin/ejbca.sh roles listadmins --role "Super Administrator Role" | grep -v 'USERNAME TYPE_EQUALCASE "ejbca"') ]]; do sleep 5; done
                    sleep 5
                    /opt/keyfactor/bin/ejbca.sh ra setpwd 'superadmin' '{{ .Values.ejbca.superadminPasswordOverride }}'
                    {{- end }}
          ports:
            {{- if .Values.services.directHttp.enabled }}
            {{- if .Values.services.directHttp.httpPort }}
            - name: http
              containerPort: 8080
              protocol: TCP
            {{- end }}
            {{- if .Values.services.directHttp.httpsPort }}  
            - name: https
              containerPort: 8443
              protocol: TCP
            {{- end }}
            {{- end }}
            {{- if .Values.services.proxyAJP.enabled }}
            - name: ajp
              containerPort: 8009
              protocol: TCP
            {{- end }}
            {{- if .Values.services.proxyHttp.enabled }}
            {{- if .Values.services.proxyHttp.httpPort }}
            - name: proxy-http
              containerPort: 8081
              protocol: TCP
            {{- end }}
            {{- if .Values.services.proxyHttp.httpsPort }}  
            - name: proxy-https
              containerPort: 8082
              protocol: TCP
            {{- end }}
            {{- end }}
          startupProbe:
            tcpSocket:
              {{- if .Values.services.directHttp.enabled }}
              port: 8443
              {{- else if .Values.services.proxyAJP.enabled }}
              port: 8009
              {{- else if .Values.services.proxyHttp.enabled }}
              port: 8082
              {{- end }}
            initialDelaySeconds: 15
            periodSeconds: 2
            failureThreshold: 500
          livenessProbe:
            tcpSocket:
              {{- if .Values.services.directHttp.enabled }}
              port: 8443
              {{- else if .Values.services.proxyAJP.enabled }}
              port: 8009
              {{- else if .Values.services.proxyHttp.enabled }}
              port: 8082
              {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.ejbca.useH2Persistence }}
            - name: ejbca-h2-persistence
              mountPath: /mnt/persistent/
            {{- end }}
            {{- if .Values.ejbca.importExternalCas }}
            - name: ejbca-config-external-cas
              mountPath: /mnt/external/secrets/tls/cas/
            {{- end }}
            {{- if .Values.ejbca.importAppserverKeystore }}
            - name: ejbca-config-appserver-keystore
              mountPath: /mnt/external/secrets/tls/ks/
            {{- end }}
            {{- if .Values.ejbca.importAppserverTruststore }}
            - name: ejbca-config-appserver-truststore
              mountPath: /mnt/external/secrets/tls/ts/
            {{- end }}
            {{- if .Values.ejbca.importEjbcaConfFiles }}
            - name: ejbca-config-conf-files
              mountPath: /opt/keyfactor/ejbca/conf/
            {{- end }}
            {{- if .Values.ejbca.importConfigdumpStaged }}
            - name: ejbca-config-configdump-staged
              mountPath: /opt/keyfactor/configdump/staged.d/
            {{- end }}
            {{- if .Values.ejbca.importConfigdumpInitialize }}
            - name: ejbca-config-configdump-initialize
              mountPath: /opt/keyfactor/configdump/initialize.d/
            {{- end }}
            {{- if .Values.ejbca.volumeMounts }}
              {{- toYaml .Values.ejbca.volumeMounts | nindent 12 }}
            {{- end }}
          {{- if .Values.ejbca.sidecarContainers }}
            {{- toYaml .Values.ejbca.sidecarContainers | nindent 8 }}
          {{- end }}
      volumes:
        {{- if .Values.ejbca.useH2Persistence }}
        - name: ejbca-h2-persistence
          persistentVolumeClaim:
            claimName: {{ .Values.ejbca.existingH2PersistenceClaim }}
        {{- end }}
        {{- if .Values.nginx.enabled }}
        - name: {{ template "ejbca.fullname" . }}-nginx-config
          configMap:
            name: {{ template "ejbca.fullname" . }}-nginx-config
        - name: nginx-cert
          emptyDir: {}
        {{- if .Values.nginx.mountInternalNginxCert }}
        - name: nginx-cert-provided
          secret:
            secretName: {{ .Values.nginx.secretInternalNginxCert }}
        {{- end }}  
        {{- end }}
        {{- if .Values.ejbca.importExternalCas }}
        - name: ejbca-config-external-cas
          secret:
            secretName: {{ .Values.ejbca.externalCasSecret }}
        {{- end }}
        {{- if .Values.ejbca.importAppserverKeystore }}
        - name: ejbca-config-appserver-keystore
          secret:
            secretName: {{ .Values.ejbca.appserverKeystoreSecret }}
        {{- end }}
        {{- if .Values.ejbca.importAppserverTruststore }}
        - name: ejbca-config-appserver-truststore
          secret:
            secretName: {{ .Values.ejbca.appserverTruststoreSecret }}
        {{- end }}
        {{- if .Values.ejbca.importEjbcaConfFiles }}
        - name: ejbca-config-conf-files
          secret:
            secretName: {{ .Values.ejbca.ejbcaConfFilesSecret }}
        {{- end }}
        {{- if .Values.ejbca.importConfigdumpStaged }}
        - name: ejbca-config-configdump-staged
          secret:
            secretName: {{ .Values.ejbca.configdumpStagedSecret }}
        {{- end }}
        {{- if .Values.ejbca.importConfigdumpInitialize }}
        - name: ejbca-config-configdump-initialize
          secret:
            secretName: {{ .Values.ejbca.configdumpInitializeSecret }}
        {{- end }}
        {{- if .Values.ejbca.volumes }}
          {{- toYaml .Values.ejbca.volumes | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName | quote }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
