{{- if .Values.nginx.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ template "ejbca.fullname" . }}-nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    {{- if .Values.nginx.service.httpPort }}
    - name: nginx-http
      port: {{ .Values.nginx.service.httpPort }}
      {{- if eq .Values.nginx.service.type "NodePort" }}
      nodePort: {{ .Values.nginx.service.httpPort }}
      {{- end }}
      targetPort: nginx-http
      protocol: TCP
    {{- end }}
    {{- if .Values.nginx.service.httpsPort }}
    - name: nginx-https
      port: {{ .Values.nginx.service.httpsPort }}
      {{- if eq .Values.nginx.service.type "NodePort" }}
      nodePort: {{ .Values.nginx.service.httpsPort }}
      {{- end }}
      targetPort: nginx-https
      protocol: TCP
    {{- end }}
  selector:
    {{- include "ejbca.selectorLabels" . | nindent 4 }}
{{- end }}
