apiVersion: v1
kind: Service
metadata:
  {{- if .Values.services.proxyHttp.annotations }}
  annotations:
    {{- range $key, $value := index .Values.services.proxyHttp.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
  name: {{ include "ejbca.fullname" . }}
  labels:
    {{- include "ejbca.labels" . | nindent 4 }}
{{- if .Values.services.directHttp.enabled }}
spec:
  type: {{ .Values.services.directHttp.type }}
  ports:
    {{- if .Values.services.directHttp.httpPort }}
    - port: {{ .Values.services.directHttp.httpPort }}
      {{- if eq .Values.services.directHttp.type "NodePort" }}
      nodePort: {{ .Values.services.directHttp.httpPort }}
      {{- end }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
    {{- if .Values.services.directHttp.httpsPort }}
    - port: {{ .Values.services.directHttp.httpsPort }}
      {{- if eq .Values.services.directHttp.type "NodePort" }}
      nodePort: {{ .Values.services.directHttp.httpsPort }}
      {{- end }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
    {{- if and .Values.ejbca.sidecarContainers .Values.services.sidecarPorts }}
      {{- toYaml .Values.services.sidecarPorts | nindent 4 }}
    {{- end }}
  selector:
    {{- include "ejbca.selectorLabels" . | nindent 4 }}
{{- end }}
{{- if .Values.services.proxyAJP.enabled }}
spec:
  type: {{ .Values.services.proxyAJP.type }}
  ports:
    - port: {{ .Values.services.proxyAJP.port }}
      {{- if eq .Values.services.proxyAJP.type "NodePort" }}
      nodePort: {{ .Values.services.proxyAJP.port }}
      {{- end }}
      targetPort: ajp
      protocol: TCP
      name: ajp
  selector:
    {{- include "ejbca.selectorLabels" . | nindent 4 }}
{{- end }}
{{- if .Values.services.proxyHttp.enabled }}
spec:
  type: {{ .Values.services.proxyHttp.type }}
  {{- if eq .Values.services.proxyHttp.type "LoadBalancer" }}
  sessionAffinity: ClientIP
  {{- end }}
  ports:
    {{- if .Values.services.proxyHttp.httpPort }}
    - port: {{ .Values.services.proxyHttp.httpPort }}
      {{- if eq .Values.services.proxyHttp.type "NodePort" }}
      nodePort: {{ .Values.services.proxyHttp.httpPort }}
      {{- end }}
      {{- if eq .Values.services.proxyHttp.type "LoadBalancer" }}
      targetPort: nginx-http
      {{- else }}
      targetPort: proxy-http
      {{- end }}
      protocol: TCP
      name: proxy-http
    {{- end }}
    {{- if .Values.services.proxyHttp.httpsPort }}
    - port: {{ .Values.services.proxyHttp.httpsPort }}
      {{- if eq .Values.services.proxyHttp.type "NodePort" }}
      nodePort: {{ .Values.services.proxyHttp.httpsPort }}
      {{- end }}
      {{- if eq .Values.services.proxyHttp.type "LoadBalancer" }}
      targetPort: nginx-https
      {{- else }}
      targetPort: proxy-http
      {{- end }}
      protocol: TCP
      name: proxy-https
    {{- end }}
  selector:
    {{- include "ejbca.selectorLabels" . | nindent 4 }}
{{- end }}
